// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QRQueueDecanat.Data;

#nullable disable

namespace QRQueueDecanat.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725090849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QRQueueDecanat.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Counter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_counters");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_counters_number");

                    b.ToTable("counters", (string)null);
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.OperatorService", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("OperatorId", "ServiceId")
                        .HasName("pk_operator_services");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_operator_services_service_id");

                    b.ToTable("operator_services", (string)null);
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.OperatorSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("pk_operator_sessions");

                    b.HasIndex("CounterId")
                        .IsUnique()
                        .HasDatabaseName("ix_operator_sessions_counter_id")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("OperatorId")
                        .IsUnique()
                        .HasDatabaseName("ix_operator_sessions_operator_id")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_operator_sessions_status_id");

                    b.ToTable("operator_sessions", (string)null);
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.OperatorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_operator_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_operator_statuses_name");

                    b.ToTable("operator_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "work"
                        },
                        new
                        {
                            Id = 2,
                            Name = "break"
                        });
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "operator"
                        });
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefix");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_services_name");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("ix_services_prefix");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_number");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_tickets_session_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_tickets_status_id");

                    b.HasIndex("ServiceDate", "DisplayNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_service_date_display_number");

                    b.HasIndex("ServiceDate", "StatusId")
                        .HasDatabaseName("ix_tickets_service_date_status_id");

                    b.HasIndex("ServiceId", "ServiceDate", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_service_id_service_date_number");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ticket_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_statuses_name");

                    b.ToTable("ticket_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "waiting"
                        },
                        new
                        {
                            Id = 2,
                            Name = "called"
                        },
                        new
                        {
                            Id = 3,
                            Name = "serving"
                        },
                        new
                        {
                            Id = 4,
                            Name = "completed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "skipped"
                        },
                        new
                        {
                            Id = 6,
                            Name = "cancelled"
                        });
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.AppUser", b =>
                {
                    b.HasOne("QRQueueDecanat.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.OperatorService", b =>
                {
                    b.HasOne("QRQueueDecanat.Entities.AppUser", "Operator")
                        .WithMany("OperatorServices")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operator_services_users_operator_id");

                    b.HasOne("QRQueueDecanat.Entities.Service", "Service")
                        .WithMany("OperatorServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operator_services_services_service_id");

                    b.Navigation("Operator");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.OperatorSession", b =>
                {
                    b.HasOne("QRQueueDecanat.Entities.Counter", "Counter")
                        .WithMany("Sessions")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operator_sessions_counters_counter_id");

                    b.HasOne("QRQueueDecanat.Entities.AppUser", "Operator")
                        .WithMany("OperatorSessions")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operator_sessions_users_operator_id");

                    b.HasOne("QRQueueDecanat.Entities.OperatorStatus", "Status")
                        .WithMany("Sessions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operator_sessions_operator_statuses_status_id");

                    b.Navigation("Counter");

                    b.Navigation("Operator");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Ticket", b =>
                {
                    b.HasOne("QRQueueDecanat.Entities.Service", "Service")
                        .WithMany("Tickets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_services_service_id");

                    b.HasOne("QRQueueDecanat.Entities.OperatorSession", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tickets_operator_sessions_session_id");

                    b.HasOne("QRQueueDecanat.Entities.TicketStatus", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_statuses_status_id");

                    b.Navigation("Service");

                    b.Navigation("Session");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.AppUser", b =>
                {
                    b.Navigation("OperatorServices");

                    b.Navigation("OperatorSessions");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Counter", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.OperatorSession", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.OperatorStatus", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.Service", b =>
                {
                    b.Navigation("OperatorServices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("QRQueueDecanat.Entities.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
